import { auth } from "@/auth";
import { LearnItContent } from "@/components/learnit/content";
import { GenerateButton } from "@/components/learnit/generate-button";
import { Prerequisites } from "@/components/learnit/prerequisites";
import { RegenerateButton } from "@/components/learnit/regenerate-button";
import { RelatedTopics } from "@/components/learnit/related-topics";
import { StreamingContent } from "@/components/learnit/streaming-content";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { getLearnItContent } from "@/lib/learnit/content-service";
import { Loader2 } from "lucide-react";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Suspense } from "react";
import { cache } from "react";

interface PageProps {
  params: Promise<{ path: string[]; }>;
}

const getLearnItContentCached = cache(getLearnItContent);

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { path } = await params;
  const slug = path.join("/").toLowerCase();
  const content = await getLearnItContentCached(slug);

  if (!content) {
    return { title: `Generate ${path.join(" ")} | LearnIt` };
  }

  return {
    title: `${content.title} | LearnIt`,
    description: content.description,
  };
}

export default async function LearnItTopicPage({ params }: PageProps) {
  const { path } = await params;
  const slug = path.join("/").toLowerCase();
  const content = await getLearnItContentCached(slug);
  const session = await auth();

  // Normalize path if needed (e.g. if user typed UPPERCASE)
  const normalizedPath = path.map(p => p.toLowerCase());
  if (path.some((p, i) => p !== normalizedPath[i])) {
    // Redirect to lowercase URL
    redirect(`/learnit/${normalizedPath.join("/")}`);
  }

  // Handle Breadcrumbs
  const breadcrumbs = path.map((segment, index) => {
    const href = `/learnit/${path.slice(0, index + 1).join("/")}`;
    return { label: segment.replace(/-/g, " "), href, isLast: index === path.length - 1 };
  });

  if (!content) {
    // If user is logged in, start streaming immediately
    // Otherwise, show the generate button which will prompt login
    if (session?.user?.id) {
      return (
        <div className="max-w-3xl mx-auto py-8 space-y-8">
          <Breadcrumbs items={breadcrumbs} />
          <header className="mb-6">
            <h1 className="text-3xl font-bold capitalize">
              {path[path.length - 1]?.replace(/-/g, " ") ?? "Topic"}
            </h1>
            <p className="text-muted-foreground mt-2">
              Generating content...
            </p>
          </header>
          <StreamingContent path={normalizedPath} />
        </div>
      );
    }

    return (
      <div className="max-w-3xl mx-auto py-8 space-y-8">
        <Breadcrumbs items={breadcrumbs} />

        <div className="py-12">
          <GenerateButton
            path={path}
            topicName={path[path.length - 1]?.replace(/-/g, " ") ?? "Topic"}
          />
        </div>
      </div>
    );
  }

  if (content.status === "GENERATING") {
    return (
      <div className="max-w-3xl mx-auto py-20 flex flex-col items-center justify-center text-center space-y-4">
        <Loader2 className="w-12 h-12 text-primary animate-spin" />
        <h2 className="text-2xl font-bold">Creating your tutorial...</h2>
        <p className="text-muted-foreground">
          This usually takes about 10-20 seconds. This page will automatically refresh.
        </p>
        {
          /* Auto-refresh meta tag or script could be added here, simplified by client refresh in GenerateButton
             but if they navigated away and came back, we need polling.
             For MVP we rely on user refresh or basic revalidation.
         */
        }
        <meta httpEquiv="refresh" content="5" />
      </div>
    );
  }

  if (content.status === "FAILED") {
    return (
      <div className="max-w-3xl mx-auto py-12 text-center">
        <h2 className="text-2xl font-bold text-destructive">Generation Failed</h2>
        <p>Something went wrong creating this content.</p>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto py-8">
      <div className="mb-6">
        <Breadcrumbs items={breadcrumbs} />
      </div>

      <header className="mb-10 pb-6 border-b">
        <h1 className="text-4xl font-extrabold tracking-tight mb-4 capitalize font-heading">
          {content.title}
        </h1>
        <p className="text-xl text-muted-foreground">{content.description}</p>
        <div className="flex items-center gap-4 mt-6 text-sm text-muted-foreground">
          <span>{content.viewCount} views</span>
          <span>•</span>
          <span>Generated by AI</span>
          {session?.user?.id && (
            <>
              <span>•</span>
              <RegenerateButton slug={slug} />
            </>
          )}
        </div>
      </header>

      {/* Prerequisites banner */}
      <Suspense fallback={null}>
        <Prerequisites topicId={content.id} className="mb-8" />
      </Suspense>

      <LearnItContent content={content.content} />

      {/* Related topics sidebar/section */}
      <Suspense fallback={null}>
        <RelatedTopics topicId={content.id} className="mt-12" />
      </Suspense>

      <div className="mt-12 pt-8 border-t text-sm text-center text-muted-foreground">
        <p>Content is AI-generated and may contain inaccuracies.</p>
      </div>
    </div>
  );
}

function Breadcrumbs({ items }: { items: { label: string; href: string; isLast: boolean; }[]; }) {
  return (
    <Breadcrumb>
      <BreadcrumbList>
        <BreadcrumbItem>
          <BreadcrumbLink href="/learnit">Home</BreadcrumbLink>
        </BreadcrumbItem>
        <BreadcrumbSeparator />
        {items.map((item) => (
          <div key={item.href} className="flex items-center gap-2">
            <BreadcrumbItem>
              {item.isLast
                ? <BreadcrumbPage className="capitalize">{item.label}</BreadcrumbPage>
                : (
                  <BreadcrumbLink href={item.href} className="capitalize">
                    {item.label}
                  </BreadcrumbLink>
                )}
            </BreadcrumbItem>
            {!item.isLast && <BreadcrumbSeparator />}
          </div>
        ))}
      </BreadcrumbList>
    </Breadcrumb>
  );
}
