# Yarn 4 configuration - using node-modules linker for maximum compatibility

# Cache settings
cacheFolder: ./.yarn/cache
compressionLevel: 9

# Node-modules linker with hardlinks for efficiency
nodeLinker: node-modules
nmMode: hardlinks-local
enableImmutableInstalls: false

# Network and build settings
networkConcurrency: 8
enableInlineBuilds: true
enableStrictSsl: true

# Security and privacy
checksumBehavior: reset
enableHardenedMode: false
enableTelemetry: false

# Audit exemptions - temporarily ignore advisories with no available fix
# GHSA-8r9q-7v3j-jr4g: ReDoS in @modelcontextprotocol/sdk <=1.25.1 (no patch available as of 2026-01-07)
# TODO: Remove this exemption once patched version is released
npmAuditIgnoreAdvisories:
  - 1111867

# Multi-platform support
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
  os:
    - linux
    - darwin
    - win32

# TypeScript integration
tsEnableAutoTypes: true

# Yarn binary location
yarnPath: .yarn/releases/yarn-4.12.0.cjs
