# Yarn 4 configuration - node-modules linker
# Uses traditional node_modules directory for maximum compatibility

# Cache settings - local cache for faster installs
cacheFolder: ./.yarn/cache
enableGlobalCache: false
compressionLevel: 9

# Linker settings - uses node_modules for compatibility
nodeLinker: node-modules
pnpMode: loose
enableImmutableInstalls: true

# Network and build settings
networkConcurrency: 8
enableInlineBuilds: true
enableStrictSsl: true

# Security and privacy
checksumBehavior: reset
enableHardenedMode: false
enableTelemetry: false

# Audit exemptions - temporarily ignore advisories with no available fix
# GHSA-8r9q-7v3j-jr4g: ReDoS in @modelcontextprotocol/sdk <=1.25.1 (no patch available as of 2026-01-07)
# TODO: Remove this exemption once patched version is released
npmAuditIgnoreAdvisories:
  - 1111867

# Multi-platform support - include glibc for Vercel/Linux deployments
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - linux
    - darwin
    - win32

# TypeScript integration
tsEnableAutoTypes: true

# Yarn binary location
yarnPath: .yarn/releases/yarn-4.12.0.cjs

# Package extensions for compatibility (add missing peer dependencies)
packageExtensions:
  "@prisma/client@*":
    dependencies:
      "@prisma/engines": "*"
  # Fix: @acemir/cssom requires cssstyle but doesn't declare it
  # Both are jsdom dependencies, but @acemir/cssom internally imports cssstyle
  "@acemir/cssom@*":
    dependencies:
      cssstyle: "*"
  # Fix: vite uses ms (via debug) but doesn't declare it
  vite@*:
    dependencies:
      ms: "*"
  # Fix: mz uses graceful-fs but doesn't declare it
  mz@*:
    dependencies:
      graceful-fs: "*"
