# Yarn 4 configuration - using node-modules linker for maximum compatibility

# Cache settings
cacheFolder: ./.yarn/cache
enableGlobalCache: false
compressionLevel: 0

# Node-modules linker (not PnP)
nodeLinker: node-modules
nmHoistingLimits: workspaces
nmMode: hardlinks-local

# Network and build settings
networkConcurrency: 8
enableInlineBuilds: true
enableStrictSsl: true

# Security and privacy
checksumBehavior: reset
enableHardenedMode: false
enableTelemetry: false

# Multi-platform support
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
  os:
    - linux
    - darwin
    - win32

# TypeScript integration
tsEnableAutoTypes: true

# Yarn binary location
yarnPath: .yarn/releases/yarn-4.12.0.cjs
