import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile, useCurrentFrame } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";
import { slide } from "@remotion/transitions/slide";
import { 
  Scene01_Struggle, 
  Scene02_Algorithm, 
  Scene03_Revealed, 
  Scene04_Features, 
  Scene05_Transformation, 
  Scene06_Testimony, 
  Scene07_CTA 
} from "./index";
import { WordHighlightCaption } from "../../components/captions/WordHighlightCaption";
import { BRIDGEMIND_DURATIONS, BRIDGEMIND_TIMING } from "../../lib/constants";
import { FormatProvider } from "../../lib/format-context";
import { interpolate } from "remotion";

/**
 * Utility to duck music volume when voiceover is playing
 */
const musicVolumeAtFrame = (
  frame: number, 
  totalFrames: number,
  _baseVolume: number = 0.2, 
  duckVolume: number = 0.05
) => {
  // Simple ducking: lower volume during the main narration scenes (0 to 1800)
  // We can refine this to specific ranges per scene
  return interpolate(
    frame,
    [0, 30, totalFrames - 30, totalFrames],
    [duckVolume, duckVolume, duckVolume, duckVolume], // Always ducked for now
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );
};

// Placeholder narration data - will be updated in Phase 3
// narration data generated by scripts/calculate-timings.ts
const NARRATION_DATA = {
  words: [
    { "text": "AI", "start_time": 0, "end_time": 0.32851851851851853 },
    { "text": "agents", "start_time": 0.32851851851851853, "end_time": 0.6570370370370371 },
    { "text": "are", "start_time": 0.6570370370370371, "end_time": 0.9855555555555556 },
    { "text": "amazing", "start_time": 0.9855555555555555, "end_time": 1.3140740740740742 },
    { "text": "at", "start_time": 1.314074074074074, "end_time": 1.6425925925925925 },
    { "text": "planning", "start_time": 1.6425925925925925, "end_time": 1.971111111111111 },
    { "text": "but", "start_time": 1.971111111111111, "end_time": 2.2996296296296294 },
    { "text": "there’s", "start_time": 2.2996296296296294, "end_time": 2.628148148148148 },
    { "text": "a", "start_time": 2.628148148148148, "end_time": 2.956666666666667 },
    { "text": "massive", "start_time": 2.9566666666666666, "end_time": 3.2851851851851856 },
    { "text": "gap", "start_time": 3.285185185185185, "end_time": 3.6137037037037042 },
    { "text": "You", "start_time": 3.6137037037037038, "end_time": 3.9422222222222224 },
    { "text": "generate", "start_time": 3.942222222222222, "end_time": 4.270740740740741 },
    { "text": "code", "start_time": 4.27074074074074, "end_time": 4.599259259259259 },
    { "text": "but", "start_time": 4.599259259259259, "end_time": 4.927777777777778 },
    { "text": "you", "start_time": 4.927777777777778, "end_time": 5.256296296296297 },
    { "text": "can't", "start_time": 5.256296296296296, "end_time": 5.584814814814815 },
    { "text": "see", "start_time": 5.584814814814815, "end_time": 5.913333333333334 },
    { "text": "it", "start_time": 5.913333333333334, "end_time": 6.241851851851852 },
    { "text": "running", "start_time": 6.2418518518518525, "end_time": 6.570370370370371 },
    { "text": "The", "start_time": 6.57037037037037, "end_time": 6.898888888888889 },
    { "text": "vibe", "start_time": 6.898888888888889, "end_time": 7.227407407407407 },
    { "text": "is", "start_time": 7.227407407407407, "end_time": 7.555925925925926 },
    { "text": "broken", "start_time": 7.555925925925926, "end_time": 7.884444444444445 },
    { "text": "Meet", "start_time": 9.366666666666667, "end_time": 9.802083333333334 },
    { "text": "the", "start_time": 9.802083333333334, "end_time": 10.2375 },
    { "text": "Bridge", "start_time": 10.2375, "end_time": 10.672916666666668 },
    { "text": "BridgeMind", "start_time": 10.672916666666667, "end_time": 11.108333333333334 },
    { "text": "for", "start_time": 11.108333333333334, "end_time": 11.54375 },
    { "text": "orchestrating", "start_time": 11.54375, "end_time": 11.979166666666668 },
    { "text": "the", "start_time": 11.979166666666666, "end_time": 12.414583333333334 },
    { "text": "plan", "start_time": 12.414583333333334, "end_time": 12.85 },
    { "text": "and", "start_time": 12.85, "end_time": 13.285416666666666 },
    { "text": "spike", "start_time": 13.285416666666668, "end_time": 13.720833333333335 },
    { "text": "dot", "start_time": 13.720833333333333, "end_time": 14.15625 },
    { "text": "land", "start_time": 14.15625, "end_time": 14.591666666666667 },
    { "text": "for", "start_time": 14.591666666666667, "end_time": 15.027083333333333 },
    { "text": "executing", "start_time": 15.027083333333333, "end_time": 15.462499999999999 },
    { "text": "the", "start_time": 15.4625, "end_time": 15.897916666666665 },
    { "text": "vision", "start_time": 15.897916666666667, "end_time": 16.333333333333332 },
    { "text": "One", "start_time": 16.833333333333332, "end_time": 17.176666666666666 },
    { "text": "continuous", "start_time": 17.176666666666666, "end_time": 17.52 },
    { "text": "pipeline", "start_time": 17.52, "end_time": 17.863333333333333 },
    { "text": "Plan", "start_time": 17.863333333333333, "end_time": 18.206666666666667 },
    { "text": "it", "start_time": 18.206666666666667, "end_time": 18.55 },
    { "text": "in", "start_time": 18.55, "end_time": 18.893333333333334 },
    { "text": "your", "start_time": 18.893333333333334, "end_time": 19.236666666666668 },
    { "text": "terminal", "start_time": 19.236666666666668, "end_time": 19.58 },
    { "text": "build", "start_time": 19.58, "end_time": 19.923333333333332 },
    { "text": "it", "start_time": 19.923333333333332, "end_time": 20.266666666666666 },
    { "text": "on", "start_time": 20.266666666666666, "end_time": 20.61 },
    { "text": "the", "start_time": 20.61, "end_time": 20.953333333333333 },
    { "text": "edge", "start_time": 20.953333333333333, "end_time": 21.296666666666667 },
    { "text": "and", "start_time": 21.296666666666667, "end_time": 21.64 },
    { "text": "see", "start_time": 21.64, "end_time": 21.983333333333334 },
    { "text": "results", "start_time": 21.983333333333334, "end_time": 22.326666666666668 },
    { "text": "instantly", "start_time": 22.326666666666668, "end_time": 22.67 },
    { "text": "in", "start_time": 22.67, "end_time": 23.013333333333332 },
    { "text": "your", "start_time": 23.013333333333332, "end_time": 23.356666666666666 },
    { "text": "browser", "start_time": 23.35666666666667, "end_time": 23.7 },
    { "text": "Seven", "start_time": 24.2, "end_time": 24.681944444444447 },
    { "text": "dedicated", "start_time": 24.681944444444447, "end_time": 25.16388888888889 },
    { "text": "MCP", "start_time": 25.163888888888888, "end_time": 25.645833333333332 },
    { "text": "tools", "start_time": 25.645833333333332, "end_time": 26.12777777777778 },
    { "text": "give", "start_time": 26.12777777777778, "end_time": 26.609722222222224 },
    { "text": "your", "start_time": 26.60972222222222, "end_time": 27.091666666666665 },
    { "text": "agents", "start_time": 27.091666666666665, "end_time": 27.573611111111113 },
    { "text": "direct", "start_time": 27.573611111111113, "end_time": 28.055555555555557 },
    { "text": "access", "start_time": 28.055555555555554, "end_time": 28.5375 },
    { "text": "to", "start_time": 28.5375, "end_time": 29.019444444444446 },
    { "text": "the", "start_time": 29.019444444444446, "end_time": 29.50138888888889 },
    { "text": "execution", "start_time": 29.50138888888889, "end_time": 29.983333333333338 },
    { "text": "layer", "start_time": 29.983333333333334, "end_time": 30.46527777777778 },
    { "text": "Read", "start_time": 30.46527777777778, "end_time": 30.947222222222226 },
    { "text": "code", "start_time": 30.947222222222226, "end_time": 31.42916666666667 },
    { "text": "edit", "start_time": 31.429166666666667, "end_time": 31.91111111111111 },
    { "text": "with", "start_time": 31.91111111111111, "end_time": 32.393055555555556 },
    { "text": "precision", "start_time": 32.393055555555556, "end_time": 32.87500000000001 },
    { "text": "and", "start_time": 32.875, "end_time": 33.356944444444444 },
    { "text": "preview", "start_time": 33.356944444444444, "end_time": 33.83888888888889 },
    { "text": "live—with", "start_time": 33.83888888888889, "end_time": 34.32083333333333 },
    { "text": "zero", "start_time": 34.32083333333333, "end_time": 34.80277777777778 },
    { "text": "manual", "start_time": 34.802777777777784, "end_time": 35.28472222222222 },
    { "text": "copy-paste", "start_time": 35.28472222222222, "end_time": 35.766666666666666 },
    { "text": "Instant", "start_time": 36.266666666666666, "end_time": 36.79555555555555 },
    { "text": "transpilation", "start_time": 36.79555555555555, "end_time": 37.32444444444444 },
    { "text": "Real-time", "start_time": 37.324444444444445, "end_time": 37.85333333333333 },
    { "text": "WebSocket", "start_time": 37.85333333333333, "end_time": 38.38222222222222 },
    { "text": "updates", "start_time": 38.382222222222225, "end_time": 38.91111111111111 },
    { "text": "It’s", "start_time": 38.91111111111111, "end_time": 39.43999999999999 },
    { "text": "the", "start_time": 39.440000000000005, "end_time": 39.968888888888884 },
    { "text": "infrastructure", "start_time": 39.968888888888884, "end_time": 40.49777777777777 },
    { "text": "that", "start_time": 40.49777777777778, "end_time": 41.026666666666664 },
    { "text": "turns", "start_time": 41.026666666666664, "end_time": 41.55555555555555 },
    { "text": "'agentic", "start_time": 41.55555555555556, "end_time": 42.08444444444444 },
    { "text": "coding'", "start_time": 42.08444444444444, "end_time": 42.61333333333333 },
    { "text": "into", "start_time": 42.61333333333334, "end_time": 43.14222222222222 },
    { "text": "'agentic", "start_time": 43.14222222222222, "end_time": 43.67111111111111 },
    { "text": "building'", "start_time": 43.67111111111111, "end_time": 44.199999999999996 },
    { "text": "Solo", "start_time": 44.7, "end_time": 45.18125 },
    { "text": "founders", "start_time": 45.18125, "end_time": 45.6625 },
    { "text": "are", "start_time": 45.6625, "end_time": 46.14375 },
    { "text": "building", "start_time": 46.14375, "end_time": 46.625 },
    { "text": "entire", "start_time": 46.625, "end_time": 47.10625 },
    { "text": "SaaS", "start_time": 47.10625, "end_time": 47.5875 },
    { "text": "platforms", "start_time": 47.5875, "end_time": 48.06875 },
    { "text": "with", "start_time": 48.06875, "end_time": 48.55 },
    { "text": "this", "start_time": 48.55, "end_time": 49.03125 },
    { "text": "workflow", "start_time": 49.03125, "end_time": 49.5125 },
    { "text": "today", "start_time": 49.5125, "end_time": 49.99375 },
    { "text": "It’s", "start_time": 49.99375, "end_time": 50.475 },
    { "text": "open", "start_time": 50.475, "end_time": 50.95625 },
    { "text": "standardized", "start_time": 50.95625, "end_time": 51.4375 },
    { "text": "and", "start_time": 51.4375, "end_time": 51.91875 },
    { "text": "production-ready", "start_time": 51.91875, "end_time": 52.4 },
    { "text": "Bring", "start_time": 52.9, "end_time": 53.252941176470586 },
    { "text": "your", "start_time": 53.252941176470586, "end_time": 53.60588235294117 },
    { "text": "agents", "start_time": 53.60588235294118, "end_time": 53.95882352941177 },
    { "text": "to", "start_time": 53.95882352941177, "end_time": 54.31176470588235 },
    { "text": "life", "start_time": 54.31176470588235, "end_time": 54.66470588235293 },
    { "text": "BridgeMind", "start_time": 54.66470588235294, "end_time": 55.01764705882353 },
    { "text": "plus", "start_time": 55.01764705882353, "end_time": 55.370588235294115 },
    { "text": "spike", "start_time": 55.370588235294115, "end_time": 55.7235294117647 },
    { "text": "dot", "start_time": 55.72352941176471, "end_time": 56.076470588235296 },
    { "text": "land", "start_time": 56.076470588235296, "end_time": 56.429411764705875 },
    { "text": "Start", "start_time": 56.42941176470588, "end_time": 56.78235294117647 },
    { "text": "building", "start_time": 56.78235294117647, "end_time": 57.13529411764706 },
    { "text": "at", "start_time": 57.13529411764706, "end_time": 57.48823529411764 },
    { "text": "spike", "start_time": 57.48823529411765, "end_time": 57.84117647058824 },
    { "text": "dot", "start_time": 57.84117647058824, "end_time": 58.194117647058825 },
    { "text": "land", "start_time": 58.194117647058825, "end_time": 58.547058823529404 },
    { "text": "today", "start_time": 58.54705882352941, "end_time": 58.9 }
  ]
};

export const BridgeMindPromo: React.FC = () => {
  const frame = useCurrentFrame();

  return (
    <FormatProvider>
      <AbsoluteFill style={{ background: "#000" }}>
        {/* Transitions & Scenes */}
        <TransitionSeries>
          <TransitionSeries.Sequence durationInFrames={BRIDGEMIND_DURATIONS.struggle}>
            <Scene01_Struggle />
          </TransitionSeries.Sequence>
          
          <TransitionSeries.Transition
            timing={linearTiming({ durationInFrames: BRIDGEMIND_TIMING.transitionFrames })}
            presentation={slide()}
          />
          
          <TransitionSeries.Sequence durationInFrames={BRIDGEMIND_DURATIONS.algorithm}>
            <Scene02_Algorithm />
          </TransitionSeries.Sequence>
          
          <TransitionSeries.Transition
            timing={linearTiming({ durationInFrames: BRIDGEMIND_TIMING.transitionFrames })}
            presentation={slide()}
          />
          
          <TransitionSeries.Sequence durationInFrames={BRIDGEMIND_DURATIONS.revealed}>
            <Scene03_Revealed />
          </TransitionSeries.Sequence>
          
          <TransitionSeries.Transition
            timing={linearTiming({ durationInFrames: BRIDGEMIND_TIMING.transitionFrames })}
            presentation={slide()}
          />
          
          <TransitionSeries.Sequence durationInFrames={BRIDGEMIND_DURATIONS.features}>
            <Scene04_Features />
          </TransitionSeries.Sequence>
          
          <TransitionSeries.Transition
            timing={linearTiming({ durationInFrames: BRIDGEMIND_TIMING.transitionFrames })}
            presentation={slide()}
          />
          
          <TransitionSeries.Sequence durationInFrames={BRIDGEMIND_DURATIONS.transformation}>
            <Scene05_Transformation />
          </TransitionSeries.Sequence>
          
          <TransitionSeries.Transition
            timing={linearTiming({ durationInFrames: BRIDGEMIND_TIMING.transitionFrames })}
            presentation={slide()}
          />
          
          <TransitionSeries.Sequence durationInFrames={BRIDGEMIND_DURATIONS.testimony}>
            <Scene06_Testimony />
          </TransitionSeries.Sequence>
          
          <TransitionSeries.Transition
            timing={linearTiming({ durationInFrames: BRIDGEMIND_TIMING.transitionFrames })}
            presentation={slide()}
          />
          
          <TransitionSeries.Sequence durationInFrames={BRIDGEMIND_DURATIONS.cta}>
            <Scene07_CTA />
          </TransitionSeries.Sequence>
        </TransitionSeries>

        {/* Voiceover Layers — each starts when its scene begins with 1s gap buffers */}
        <Sequence from={0}>
          <Audio src={staticFile("audio/bridgemind-scene1.mp3")} />
        </Sequence>
        <Sequence from={281}>
          <Audio src={staticFile("audio/bridgemind-scene2.mp3")} />
        </Sequence>
        <Sequence from={505}>
          <Audio src={staticFile("audio/bridgemind-scene3.mp3")} />
        </Sequence>
        <Sequence from={726}>
          <Audio src={staticFile("audio/bridgemind-scene4.mp3")} />
        </Sequence>
        <Sequence from={1088}>
          <Audio src={staticFile("audio/bridgemind-scene5.mp3")} />
        </Sequence>
        <Sequence from={1341}>
          <Audio src={staticFile("audio/bridgemind-scene6.mp3")} />
        </Sequence>
        <Sequence from={1587}>
          <Audio src={staticFile("audio/bridgemind-scene7.mp3")} />
        </Sequence>

        {/* Background Music */}
        <Audio
          src={staticFile("audio/physics-of-attention.m4a")}
          volume={(f) => musicVolumeAtFrame(f, BRIDGEMIND_TIMING.totalFrames, 0.4, 0.1)}
          loop
        />

        {/* Captions Overlay */}
        <WordHighlightCaption 
          words={NARRATION_DATA.words} 
          currentTime={frame / BRIDGEMIND_TIMING.fps} 
        />
      </AbsoluteFill>
    </FormatProvider>
  );
};
