# Yarn 4 configuration - using pnpm-style linker for efficiency + compatibility

# Cache settings
cacheFolder: ./.yarn/cache
compressionLevel: 9

# pnpm linker mode (symlinks like pnpm, more compatible than PnP)
nodeLinker: pnpm

# Network and build settings
networkConcurrency: 8
enableInlineBuilds: true
enableStrictSsl: true

# Security and privacy
checksumBehavior: reset
enableHardenedMode: false
enableTelemetry: false

# Multi-platform support
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - current
  os:
    - linux
    - darwin
    - win32

# TypeScript integration
tsEnableAutoTypes: true

# Yarn binary location
yarnPath: .yarn/releases/yarn-4.12.0.cjs
