export interface SkillDefinition {
  id: string;
  name: string;
  icon: string;
  category: string;
  colorClass: string;
  triggers: string[];
  description: string;
}

export const SKILL_DEFINITIONS: SkillDefinition[] = [
  // 3D — blue
  {
    id: "three-js",
    name: "Three.js",
    icon: "🧊",
    category: "3D",
    colorClass: "border-blue-400/30 bg-blue-500/10 text-blue-400",
    triggers: [
      "three",
      "3d",
      "globe",
      "scene",
      "orbit",
      "planet",
      "cube",
      "sphere",
      "terrain",
      "space",
      "solar",
      "earth",
      "webgl",
    ],
    description: "3D scene rendering",
  },
  {
    id: "three-perf",
    name: "3D Performance",
    icon: "🎯",
    category: "3D",
    colorClass: "border-blue-400/30 bg-blue-500/10 text-blue-400",
    triggers: [
      "three",
      "3d",
      "globe",
      "scene",
      "orbit",
      "planet",
      "cube",
      "sphere",
      "terrain",
      "space",
      "solar",
      "earth",
      "webgl",
    ],
    description: "OrbitControls and performance",
  },
  // Data Viz — green
  {
    id: "recharts",
    name: "Recharts",
    icon: "📊",
    category: "Data Viz",
    colorClass: "border-green-400/30 bg-green-500/10 text-green-400",
    triggers: [
      "chart",
      "charts",
      "dashboard",
      "analytics",
      "stats",
      "graph",
      "graphs",
      "metrics",
      "finance",
      "stock",
      "tracker",
      "data",
      "visualization",
      "reporting",
      "trending",
    ],
    description: "Interactive charts",
  },
  {
    id: "chart-ui",
    name: "Chart UI",
    icon: "📈",
    category: "Data Viz",
    colorClass: "border-green-400/30 bg-green-500/10 text-green-400",
    triggers: [
      "chart",
      "charts",
      "dashboard",
      "analytics",
      "stats",
      "graph",
      "graphs",
      "metrics",
      "finance",
      "stock",
      "tracker",
      "data",
      "visualization",
      "reporting",
      "trending",
    ],
    description: "shadcn/ui chart components",
  },
  // Game — purple
  {
    id: "canvas-confetti",
    name: "Confetti",
    icon: "🎉",
    category: "Game",
    colorClass: "border-purple-400/30 bg-purple-500/10 text-purple-400",
    triggers: [
      "game",
      "games",
      "gaming",
      "gameplay",
      "player",
      "playing",
      "play",
      "puzzle",
      "quiz",
      "tictactoe",
      "chess",
      "snake",
      "tetris",
      "wordle",
      "sudoku",
      "maze",
      "arcade",
    ],
    description: "Celebration effects",
  },
  {
    id: "howler-game",
    name: "Game Audio",
    icon: "🔊",
    category: "Game",
    colorClass: "border-purple-400/30 bg-purple-500/10 text-purple-400",
    triggers: [
      "game",
      "games",
      "gaming",
      "gameplay",
      "player",
      "playing",
      "play",
      "puzzle",
      "quiz",
      "tictactoe",
      "chess",
      "snake",
      "tetris",
      "wordle",
      "sudoku",
      "maze",
      "arcade",
    ],
    description: "Game sound effects",
  },
  // Form — orange
  {
    id: "react-hook-form",
    name: "React Hook Form",
    icon: "📝",
    category: "Form",
    colorClass: "border-orange-400/30 bg-orange-500/10 text-orange-400",
    triggers: [
      "form",
      "forms",
      "survey",
      "signup",
      "checkout",
      "wizard",
      "booking",
      "contact",
      "calculator",
      "converter",
      "registration",
    ],
    description: "Form state and validation",
  },
  {
    id: "form-ui",
    name: "Form Components",
    icon: "🎛️",
    category: "Form",
    colorClass: "border-orange-400/30 bg-orange-500/10 text-orange-400",
    triggers: [
      "form",
      "forms",
      "survey",
      "signup",
      "checkout",
      "wizard",
      "booking",
      "contact",
      "calculator",
      "converter",
      "registration",
    ],
    description: "Checkbox, switch, slider",
  },
  // DnD — cyan
  {
    id: "dnd-kit",
    name: "DnD Kit",
    icon: "🖱️",
    category: "DnD",
    colorClass: "border-cyan-400/30 bg-cyan-500/10 text-cyan-400",
    triggers: [
      "kanban",
      "board",
      "boards",
      "drag",
      "draggable",
      "sort",
      "sorting",
      "sortable",
      "reorder",
      "planner",
      "calendar",
      "schedule",
      "timeline",
      "todo",
      "todos",
      "builder",
      "rank",
    ],
    description: "Drag and drop",
  },
  // Drawing — pink
  {
    id: "roughjs",
    name: "Rough.js",
    icon: "✏️",
    category: "Drawing",
    colorClass: "border-pink-400/30 bg-pink-500/10 text-pink-400",
    triggers: [
      "draw",
      "drawing",
      "paint",
      "painting",
      "sketch",
      "canvas",
      "whiteboard",
      "doodle",
      "art",
      "artistic",
      "signature",
      "diagram",
    ],
    description: "Hand-drawn graphics",
  },
  // Content — amber
  {
    id: "react-markdown",
    name: "React Markdown",
    icon: "📄",
    category: "Content",
    colorClass: "border-amber-400/30 bg-amber-500/10 text-amber-400",
    triggers: [
      "blog",
      "blogging",
      "story",
      "stories",
      "writing",
      "note",
      "notes",
      "notebook",
      "journal",
      "recipe",
      "wiki",
      "markdown",
      "article",
      "articles",
      "portfolio",
      "gallery",
    ],
    description: "Markdown rendering",
  },
  {
    id: "content-ui",
    name: "Content UI",
    icon: "🗂️",
    category: "Content",
    colorClass: "border-amber-400/30 bg-amber-500/10 text-amber-400",
    triggers: [
      "blog",
      "blogging",
      "story",
      "stories",
      "writing",
      "note",
      "notes",
      "notebook",
      "journal",
      "recipe",
      "wiki",
      "markdown",
      "article",
      "articles",
      "portfolio",
      "gallery",
    ],
    description: "Accordion, table, pagination",
  },
  // Audio — red
  {
    id: "howler",
    name: "Howler.js",
    icon: "🎵",
    category: "Audio",
    colorClass: "border-red-400/30 bg-red-500/10 text-red-400",
    triggers: [
      "music",
      "musical",
      "audio",
      "sound",
      "beat",
      "beats",
      "drum",
      "drums",
      "piano",
      "instrument",
      "synth",
      "metronome",
      "rhythm",
      "melody",
      "guitar",
    ],
    description: "Audio playback",
  },
  {
    id: "web-audio",
    name: "Web Audio",
    icon: "🎹",
    category: "Audio",
    colorClass: "border-red-400/30 bg-red-500/10 text-red-400",
    triggers: [
      "music",
      "musical",
      "audio",
      "sound",
      "beat",
      "beats",
      "drum",
      "drums",
      "piano",
      "instrument",
      "synth",
      "metronome",
      "rhythm",
      "melody",
      "guitar",
    ],
    description: "Audio synthesis",
  },
  // URL Params — slate
  {
    id: "url-params",
    name: "URL Params",
    icon: "🔗",
    category: "URL Params",
    colorClass: "border-slate-400/30 bg-slate-500/10 text-slate-400",
    triggers: ["dashboard", "tracker", "monitor", "analytics", "config", "settings"],
    description: "Shareable URL state",
  },
];

export const FALLBACK_SKILL: SkillDefinition = {
  id: "general",
  name: "General",
  icon: "✨",
  category: "General",
  colorClass: "border-gray-400/30 bg-gray-500/10 text-gray-400",
  triggers: [],
  description: "General-purpose app",
};
