import {
  Accessibility,
  AlertTriangle,
  Bell,
  Component,
  Layers,
  LayoutGrid,
  Loader,
  MousePointerClick,
  Palette,
  PanelTop,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  SplitSquareHorizontal,
  Table2,
  Type,
} from "lucide-react";

export const storybookIconMap = {
  Sparkles,
  Palette,
  Type,
  MousePointerClick,
  Component,
  SplitSquareHorizontal,
  Bell,
  Loader,
  PanelTop,
  Accessibility,
  Table2,
  LayoutGrid,
  ShoppingBag,
  Layers,
  ShieldCheck,
  AlertTriangle,
};

export const colorPalette = {
  brand: [
    {
      name: "spike.land Violet",
      var: "--pixel-cyan",
      hex: "#8B5CF6",
      desc: "Primary brand accent colors (Nebula Violet)",
      role: "Primary",
      contrastPass: true,
    },
    {
      name: "spike.land Pink",
      var: "--pixel-fuchsia",
      hex: "#EC4899",
      desc: "Secondary accent (Nebula Pink)",
      role: "Secondary",
      contrastPass: true,
    },
  ],
  dark: [
    {
      name: "Slate Surface",
      var: "--card",
      hex: "#1E293B",
      desc: "Card backgrounds",
    },
    {
      name: "Border",
      var: "--border",
      hex: "#334155",
      desc: "Primary borders",
    },
    {
      name: "Border Item",
      var: "--border-item",
      hex: "#334155",
      desc: "Item borders",
    },
    {
      name: "Deep Slate",
      var: "--background",
      hex: "#0F172A",
      desc: "Dark background",
    },
    {
      name: "Text Muted",
      var: "--muted-foreground",
      hex: "#94A3B8",
      desc: "Secondary text",
    },
  ],
  light: [
    {
      name: "Clean White",
      var: "--background",
      hex: "#FFFFFF",
      desc: "Light background",
    },
    {
      name: "Light Surface",
      var: "--card",
      hex: "#F4F6F8",
      desc: "Light cards",
    },
    {
      name: "Carbon Text",
      var: "--foreground",
      hex: "#12121C",
      desc: "Primary text",
    },
    {
      name: "Grid Grey",
      var: "--border",
      hex: "#DCE0E8",
      desc: "Light borders",
    },
  ],
};

export const logoSizes = ["sm", "md", "lg", "xl"] as const;
export const logoVariants = ["icon", "horizontal", "stacked"] as const;
export const buttonVariants = [
  "default",
  "secondary",
  "outline",
  "ghost",
  "destructive",
  "link",
] as const;
export const buttonSizes = ["sm", "default", "lg", "icon"] as const;

export const storybookSections = [
  {
    id: "brand",
    label: "Brand",
    category: "Foundation",
    description: "Logo variants, sizes, and the spike.land AI Spark logo",
    icon: "Sparkles",
  },
  {
    id: "colors",
    label: "Colors",
    category: "Foundation",
    description: "Color palette, brand colors, dark/light modes, glow effects",
    icon: "Palette",
  },
  {
    id: "typography",
    label: "Typography",
    category: "Foundation",
    description: "Font families, heading scale, text colors",
    icon: "Type",
  },
  {
    id: "surfaces",
    label: "Surfaces",
    category: "Foundation",
    description: "Glass-morphism tiers, elevation system, and transparency",
    icon: "Layers",
  },
  {
    id: "buttons",
    label: "Buttons",
    category: "Actions",
    description: "Button variants, sizes, states, loading indicators",
    icon: "MousePointerClick",
  },
  {
    id: "components",
    label: "Components",
    category: "Elements",
    description: "Cards, badges, inputs, accordion, tabs, textarea, tooltip, slider",
    icon: "Component",
  },
  {
    id: "data-display",
    label: "Data Display",
    category: "Data",
    description: "Tables, toggle groups, and copy buttons",
    icon: "Table2",
  },
  {
    id: "layout",
    label: "Layout",
    category: "Structure",
    description: "Masonry grid, text overlays, and zoom controls",
    icon: "LayoutGrid",
  },
  {
    id: "comparison",
    label: "Comparison",
    category: "Elements",
    description: "Image comparison slider, comparison view toggle",
    icon: "SplitSquareHorizontal",
  },
  {
    id: "feedback",
    label: "Feedback",
    category: "Status",
    description: "Toast notifications, alerts, semantic state colors",
    icon: "Bell",
  },
  {
    id: "loading",
    label: "Loading",
    category: "Status",
    description: "Skeleton loaders, progress bars, spinners/animations",
    icon: "Loader",
  },
  {
    id: "modals",
    label: "Modals",
    category: "Overlays",
    description: "Dialogs, dropdown menus, sheets, alert dialogs",
    icon: "PanelTop",
  },
  {
    id: "accessibility",
    label: "Accessibility",
    category: "Principles",
    description: "Contrast checker, keyboard navigation, ARIA attributes",
    icon: "Accessibility",
  },
  {
    id: "merch",
    label: "Merch",
    category: "Features",
    description: "Print-on-demand merchandise components",
    icon: "ShoppingBag",
  },
  {
    id: "photo-mix",
    label: "PhotoMix",
    category: "Features",
    description: "Photo mixing and blending components",
    icon: "Layers",
  },
  {
    id: "auth",
    label: "Auth",
    category: "Systems",
    description: "Authentication components, buttons, and user avatars",
    icon: "ShieldCheck",
  },
  {
    id: "errors",
    label: "Errors",
    category: "Systems",
    description: "Error handling components and error boundaries",
    icon: "AlertTriangle",
  },
] as const;
