name: Publish MCP Server to npm

on:
  push:
    tags:
      - 'mcp-server-v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 0.1.0)'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for npm provenance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          cd packages/mcp-server
          npm ci

      - name: Build package
        run: |
          cd packages/mcp-server
          npm run build

      - name: Verify build output
        run: |
          cd packages/mcp-server
          ls -la dist/
          test -f dist/index.js || (echo "Build failed: dist/index.js not found" && exit 1)
          test -f dist/index.d.ts || (echo "Build failed: dist/index.d.ts not found" && exit 1)

      - name: Update version (if workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd packages/mcp-server
          npm version ${{ inputs.version }} --no-git-tag-version

      - name: Publish to npm
        run: |
          cd packages/mcp-server
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            const version = tag.replace('mcp-server-v', '');

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              name: `MCP Server v${version}`,
              body: `## @spike-land/mcp-server v${version}

Published to npm: https://www.npmjs.com/package/@spike-land/mcp-server

### Installation
\`\`\`bash
npx @spike-land/mcp-server
\`\`\`

### Documentation
- [MCP Tools Documentation](https://spike.land/apps/pixel/mcp-tools)
- [API Key Setup](https://spike.land/settings)
`,
              draft: false,
              prerelease: version.includes('-')
            });
