// Auto-generated by scripts/generate-audio.ts — do not edit manually
// Run `npx tsx packages/video/scripts/generate-audio.ts` to regenerate
import type { NarrationWord } from "./narration";

export interface SceneTimestamps {
  sceneId: string;
  words: NarrationWord[];
  audioDurationSeconds: number;
}

// Placeholder — will be populated after running generate-audio.ts
export const NARRATION_TIMESTAMPS: Record<string, SceneTimestamps> = {};
