/**
 * Mock for @tamagui/shorthands
 */

export const shorthands = {
  p: "padding",
  px: "paddingHorizontal",
  py: "paddingVertical",
  pt: "paddingTop",
  pb: "paddingBottom",
  pl: "paddingLeft",
  pr: "paddingRight",
  m: "margin",
  mx: "marginHorizontal",
  my: "marginVertical",
  mt: "marginTop",
  mb: "marginBottom",
  ml: "marginLeft",
  mr: "marginRight",
  bg: "backgroundColor",
  br: "borderRadius",
  bw: "borderWidth",
  bc: "borderColor",
  f: "flex",
  fd: "flexDirection",
  fw: "flexWrap",
  ai: "alignItems",
  ac: "alignContent",
  as: "alignSelf",
  jc: "justifyContent",
  w: "width",
  h: "height",
  minW: "minWidth",
  maxW: "maxWidth",
  minH: "minHeight",
  maxH: "maxHeight",
  pos: "position",
  zi: "zIndex",
  o: "opacity",
  ov: "overflow",
  ta: "textAlign",
  col: "color",
  ff: "fontFamily",
  fs: "fontSize",
  lh: "lineHeight",
  ls: "letterSpacing",
} as const;

export default { shorthands };
